### ISSUE TITLE
output bam without FR or RR tag

### ISSUE THREAD

**Issue by Frank1219** [OpenGene/gencore#37]
Hi, I used this software with the cmd: gencore -i xx.fastp.sort.bam -o xx.gencore.bam -r hg19.fasta -s 1 --high_qual 30. However, there is no information about FR or RR tag in the output bam, is there something wrong with my cmd? Can you give me some suggestions? thanks so much.

**Comment by Frank1219** [comment]
Hi, I got the same result with the new version v0.17.0 installed by conda, what is the reason about this? my bam was like this, please have a look: A00289:372:HY5C3DMXX:2:1328:19126:33082:CGG_TAT 0       chrM    1       60      5S91M   *       0       0       CGATGGATCACAGGTCTATCACCCTATTAACCACTCACGGGAGCTCTCCATGCATTTGGTATTTTCGTCTGGGGGGTGTGCACGCGATAGCATTGC        FFFFFFFFFFFFFFFFFF,FFFFFF,FFFFF:FFFFFFFFFFFFFFFF,,FF:F:FFFFFF:FF,FFFF,FFFFFFFFFFFFFFFFF:FFFFFFFF        NM:i:0  MD:Z:91 AS:i:91 XS:i:65
A00289:372:HY5C3DMXX:2:1344:23321:5212:CGG_TAT  0       chrM    1       60      5S49M   *       0       0       CGATGGATCACAGGTCTATCACCCTATTAACCACTCACGGGAGCTCTCCATGCA  :FF,FF,,FFFF:F,:FF:FF::F,F,FFFF,FFF:FF:F:F:FFF,F:F:,F:  NM:i:0  MD:Z:49 AS:i:49 XS:i:0
A00289:372:HY5C3DMXX:2:1287:6894:31751:ATC_AGC  0       chrM    112     60      96M     *       0       0       CCCTATGTCGCAGTATCTGTCTTTGATTCCTGCCTCATTCTATTATTTATCGCACCTACGTTCAATATTACAGGCGAACATACTTACTAAAGTGTG        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFF:FFFF        NM:i:1  MD:Z:83C12      AS:i:91 XS:i:0

**Comment by sfchen** [comment]
Is this the output bam? Or the input bam?

Can you paste the output results?

**Comment by Frank1219** [comment]
That was the input bam, the output bam like this: 
A00289:372:HY5C3DMXX:2:1344:23321:5212:CGG_TAT  0       chrM    1       60      5S49M   *       0       0       CGATGGATCACAGGTCTATCACCCTATTAACCACTCACGGGAGCTCTCCATGCA  :FF,FF,,FFFF:F,:FF:FF::F,F,FFFF,FFF:FF:F:F:FFF,F:F:,F:  NM:i:0  MD:Z:49 AS:i:49 XS:i:0
A00289:372:HY5C3DMXX:2:1328:19126:33082:CGG_TAT 0       chrM    1       60      5S91M   *       0       0       CGATGGATCACAGGTCTATCACCCTATTAACCACTCACGGGAGCTCTCCATGCATTTGGTATTTTCGTCTGGGGGGTGTGCACGCGATAGCATTGC        FFFFFFFFFFFFFFFFFF,FFFFFF,FFFFF:FFFFFFFFFFFFFFFF,,FF:F:FFFFFF:FF,FFFF,FFFFFFFFFFFFFFFFF:FFFFFFFF        NM:i:0  MD:Z:91 AS:i:91 XS:i:65
A00289:372:HY5C3DMXX:2:1287:6894:31751:ATC_AGC  0       chrM    112     60      96M     *       0       0       CCCTATGTCGCAGTATCTGTCTTTGATTCCTGCCTCATTCTATTATTTATCGCACCTACGTTCAATATTACAGGCGAACATACTTACTAAAGTGTG        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFF:FFFF        NM:i:1  MD:Z:83C12      AS:i:91 XS:i:0

**Comment by sfchen** [comment]
> > What's you command, and the command output?
> 
> This is the cmd: gencore -i xx.fastp.sort.bam -o xx.gencore.bam -r hg19.fasta -s 1 --high_qual 30

And what's the output in the shell?

**Comment by sfchen** [comment]
Is your data single-end or paired-end ?

**Comment by Frank1219** [comment]
> My data was paired-end and I do not know why it remind me that, and the bwa cmd was "bwa mem -p -M -t 8 hg19.fasta xx.R1.fastq.gz xx.R2.fastq.gz |samtools view -bS - > xx.fastp.bam", after that sort the bam with the cmd "samtools sort -@ 4 -o xx.fastp.sort.bam xx.fastp.bam". Is there something wrong with my cmd?

I'm sorry to bother you, but the question several days still not solved and I don't know where is the problem, could you give me some suggestions?

**Comment by Frank1219** [comment]
> Thanks for your reply. This is my data, please hava a try. [test.zip](https://github.com/OpenGene/gencore/files/7353836/test.zip)

Hi, is there something wrong when running the software ?
