### ISSUE TITLE
The software installation is not working properly.

### ISSUE THREAD

**Issue by ChaoXianSen** [OpenGene/gencore#40]
# this binary was compiled on CentOS, and tested on CentOS/Ubuntu
wget http://opengene.org/gencore/gencore
chmod a+x ./gencore

#### I try the above method, but, I can not use this software. 
Server report an error:
$  ./gencore
./gencore: error while loading shared libraries: libhts.so.2: cannot open shared object file: No such file or directory

**Comment by sfchen** [comment]
fixed
