### ISSUE TITLE
'=' symbol in the BAM/CRAM SEQ field

### ISSUE THREAD

**Issue by ShannonDaddy** [OpenGene/gencore#46]
Hi，after I use gencore 0.17.2 to process my bam file, I found '=' symbol in a consensus read sequence as follows:
![c0770a42d8da6271c3391ce7e453fcc](https://user-images.githubusercontent.com/6656888/202142565-d8c4eea3-bdbe-4ff0-b006-18b7d71857ab.jpg)

my command is like this:
![image](https://user-images.githubusercontent.com/6656888/202142892-a2ea71bb-0536-43b8-9c21-249223258773.png)

please help me out, thnaks!

**Comment by robinjugas** [comment]
Hi, I have the same issue.

**Comment by jammywwh** [comment]
same issue
someone else can help me?

**Comment by biolxy** [comment]
I have the same issue. When sequences in Reads1 and Reads2 are inconsistent, the inconsistent site(base) is set to '='
